export const FETCH_STARTED = "FETCH_STARTED";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILED = "FETCH_FAILED";

export const SET_CURRENT_WEATHER = "SET_CURRENT_WEATHER";
export const SET_FORECAST_WEATHER = "SET_FORECAST_WEATHER";

export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
