export const FETCH_STARTED = "FETCH_STARTED";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILED = "FETCH_FAILED";

export const SET_CORRENT_WEATHER = "SET_CORRENT_WEATHER";
export const SET_FORECAST_WEATHER = "SET_FORECAST_WEATHER";
