export const FETCH_STARTED = "FETCH_STARTED";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILED = "FETCH_FAILED";

export const SET_CURRENT_WEATHER = "SET_CURRENT_WEATHER";
export const SET_FORECAST_WEATHER = "SET_FORECAST_WEATHER";

export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export const SET_ALL_FAVORITES = "SET_ALL_FAVORITES";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";

export const FETCH_FAVORITE_STARTED = "FETCH_FAVORITE_STARTED";
export const FETCH_FAVORITE_SUCCESS = "FETCH_FAVORITE_SUCCESS";
export const FETCH_FAVORITE_FAILED = "FETCH_FAVORITE_FAILED";

export const SET_FAVORITE_CURRENT_WEATHER = "SET_FAVORITE_CURRENT_WEATHER";

export const CHANGE_THEME = "CHANGE_THEME";
export const CHANGE_UNIT = "CHANGE_UNIT";
